INSERT INTO teams VALUES(NULL, "FOR");
INSERT INTO teams VALUES(NULL, "ANA");
INSERT INTO teams VALUES(NULL, "MIC");
INSERT INTO teams VALUES(NULL, "PRO");

INSERT INTO work_types VALUES(NULL, "MA");
INSERT INTO work_types VALUES(NULL, "ES");
INSERT INTO work_types VALUES(NULL, "IC");
INSERT INTO work_types VALUES(NULL, "PT");
INSERT INTO work_types VALUES(NULL, "PP");